features:
  properties:
    divergent-analysis-days: 3
    expire-post-code-days: 10
    expirePostCodeScheduler: "*/40 * * * * *"
    acceptPendingDivergentAnalysisScheduler: "0 10 15 * * *"

cron:
  schedulers:
    divergent-analysis:
      days: 3
      cron-expression: "0 0/1 * * * ?"
      enabled: true
    expire-post-code:
      days: 15
      cron-expression: "0 0/5 * * * ?"
      enabled: false
